# argument for Go version
ARG GO_VERSION=1.22.7

FROM golang:${GO_VERSION} AS builder


# get air
RUN curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/master/install.sh \
    && chmod +x install.sh && sh install.sh && cp ./bin/air /bin/air

# change workspace
WORKDIR /go/src/app
ADD . /go/src/app

WORKDIR /go/src/app/

CMD air -c .air.core.toml
